### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(cmake-build-debug)
add_subdirectory(Launcher)
add_subdirectory(LauncherContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "cmake-build-debug/qml/LauncherContent/fonts/SpaceMono-Bold.ttf"
        "cmake-build-debug/qml/LauncherContent/fonts/SpaceMono-BoldItalic.ttf"
        "cmake-build-debug/qml/LauncherContent/fonts/SpaceMono-Italic.ttf"
        "cmake-build-debug/qml/LauncherContent/fonts/SpaceMono-Regular.ttf"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    LauncherContentplugin
    Launcherplugin
    LauncherContentplugin
    QtQuickDesignerComponents)